CREATE TABLE IF NOT EXISTS projects(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name TEXT NOT NULL CHECK (name <> ''),
	priority integer NOT NULL,
	description text,
	deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name TEXT NOT NULL CHECK (name <> ''),
	done BOOLEAN,
	projectid INTEGER REFERENCES projects(id)
);

-- Some rows for projects
INSERT INTO projects(name, priority, description, deliverydate)
	VALUES('Make ecommerce', 1, 'Make shop with JS', '2019-09-15');

INSERT INTO projects(name, priority, description, deliverydate)
	VALUES('Make house', 1, 'Make house with rocks', '2020-05-05');

INSERT INTO projects(name, priority, description, deliverydate)
	VALUES('Make mobile app', 2, 'Make app with flutter', '2019-10-10');

-- Some rows for taks
INSERT INTO tasks(name, done, projectid)
	VALUES('Download Angular', false, 1);

INSERT INTO tasks(name, done, projectid)
	VALUES('Create UI', false, 1);

INSERT INTO tasks(name, done, projectid)
	VALUES('Design the house', false, 2);

INSERT INTO tasks(name, done, projectid)
	VALUES('Get materials', false, 2);

INSERT INTO tasks(name, done, projectid)
	VALUES('Download Flutter', false, 3);

INSERT INTO tasks(name, done, projectid)
	VALUES('Create the widgets', false, 3);
